export const Routes = {
    // pages/screen
    Login: { path: "/login" },
    Register: { path: "/register" },
    ForgotPassword: { path: "/forgot-password" },
    NotFound: { path: "/404" },
    ServerError: { path: "/500" },
    ResetPassword: { path: "/reset-password" },
    Lock: { path: "/lock" },
    Dashboard: { path: "/home" },
    Classroom: { path: "/classroom" },
    Subject: { path: "/subjects" },
    Assignment: { path: "/assignments" },
    Quiz: { path: "/quizzes" },
    MotivationalQuote: { path: "/motivational-quote" },
    User: { path: "/users" },
    Settings: { path: "/settings" },
    Student: { path: "/students" },
    Tutor: { path: "/tutors" },
    Admin: { path: "/admin" },
};